with-expecter: true
resolve-type-alias: false
disable-version-string: true
issue-845-fix: true
log-level: error
packages:
  github.com/jekabolt/grbpwr-manager/internal/dependency:
    config:
      filename: "mock_{{.InterfaceName}}.go"
      dir: "{{.InterfaceDir}}/mocks"
      mockname: "{{.InterfaceName}}"
    interfaces:
      ContextStore:
      Products:
      Hero:
      Mail:
      Order:
      Invoicer:
      StripePayment:
      Trongrid:
      Subscribers:
      Support:
      Promo:
      Rates:
      Archive:
      Language:
      Media:
      Admin:
      Settings:
      Repository:
      Cache:
      DB:
      FileStore:
      RatesService:
      RevalidationService:
      Mailer:
      Sender:
      PaymentPool:
