version: '3.4' # Using version 3.4 to ensure healthcheck support

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: 'grbpwr'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'pass'
      MYSQL_ROOT_PASSWORD: 'pass'
      MYSQL_TCP_PORT: 3306
    ports:
      - '3306:3306'
    networks:
      - grbpwr-network

  product_manager:
    image: grbpwr/grbpwr-pm:master
    ports:
      - '8081:8081'
    depends_on:
      - db
    networks:
      - grbpwr-network

volumes:
  my-db:


networks:
  grbpwr-network:
