// Code generated by internal/betaseed/gen. DO NOT EDIT.
package betaseed

import (
	"context"

	admin "github.com/jekabolt/grbpwr-manager/proto/gen/admin"
	auth "github.com/jekabolt/grbpwr-manager/proto/gen/auth"
	frontend "github.com/jekabolt/grbpwr-manager/proto/gen/frontend"
)

var _ = context.Background

// ---- admin (242 rpc) ----

func (c *Client) AddArchive(ctx context.Context, in *admin.AddArchiveRequest) (*admin.AddArchiveResponse, error) {
	out := new(admin.AddArchiveResponse)
	if err := c.call(ctx, "POST", "/api/admin/archive/add", in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) AddFitting(ctx context.Context, in *admin.AddFittingRequest) (*admin.AddFittingResponse, error) {
	out := new(admin.AddFittingResponse)
	if err := c.call(ctx, "POST", "/api/admin/fitting/add", in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) AddFittingChangeRequest(ctx context.Context, in *admin.AddFittingChangeRequestRequest) (*admin.AddFittingChangeRequestResponse, error) {
	out := new(admin.AddFittingChangeRequestResponse)
	if err := c.call(ctx, "POST", "/api/admin/fitting/change-request/add", in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) AddFulfillmentChecklistItem(ctx context.Context, in *admin.AddFulfillmentChecklistItemRequest) (*admin.AddFulfillmentChecklistItemResponse, error) {
	out := new(admin.AddFulfillmentChecklistItemResponse)
	if err := c.call(ctx, "POST", "/api/admin/fulfillment/checklist/add", in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) AddHero(ctx context.Context, in *admin.AddHeroRequest) (*admin.AddHeroResponse, error) {
	out := new(admin.AddHeroResponse)
	if err := c.call(ctx, "POST", "/api/admin/hero/add", in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) AddMaterialPrice(ctx context.Context, in *admin.AddMaterialPriceRequest) (*admin.AddMaterialPriceResponse, error) {
	out := new(admin.AddMaterialPriceResponse)
	if err := c.call(ctx, "POST", "/api/admin/materials/price", in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) AddModel(ctx context.Context, in *admin.AddModelRequest) (*admin.AddModelResponse, error) {
	out := new(admin.AddModelResponse)
	if err := c.call(ctx, "POST", "/api/admin/model/add", in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) AddOrderComment(ctx context.Context, in *admin.AddOrderCommentRequest) (*admin.AddOrderCommentResponse, error) {
	out := new(admin.AddOrderCommentResponse)
	if err := c.call(ctx, "POST", "/api/admin/orders/{order_uuid}/comment", in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) AddPromo(ctx context.Context, in *admin.AddPromoRequest) (*admin.AddPromoResponse, error) {
	out := new(admin.AddPromoResponse)
	if err := c.call(ctx, "POST", "/api/admin/promo/add", in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) AddSample(ctx context.Context, in *admin.AddSampleRequest) (*admin.AddSampleResponse, error) {
	out := new(admin.AddSampleResponse)
	if err := c.call(ctx, "POST", "/api/admin/sample/add", in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) AddSampleSubstitution(ctx context.Context, in *admin.AddSampleSubstitutionRequest) (*admin.AddSampleSubstitutionResponse, error) {
	out := new(admin.AddSampleSubstitutionResponse)
	if err := c.call(ctx, "POST", "/api/admin/sample/substitution/add", in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) AddShipmentCarrier(ctx context.Context, in *admin.AddShipmentCarrierRequest) (*admin.AddShipmentCarrierResponse, error) {
	out := new(admin.AddShipmentCarrierResponse)
	if err := c.call(ctx, "POST", "/api/admin/settings/shipment-carrier/add", in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) AddTask(ctx context.Context, in *admin.AddTaskRequest) (*admin.AddTaskResponse, error) {
	out := new(admin.AddTaskResponse)
	if err := c.call(ctx, "POST", "/api/admin/task/add", in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) AddTaskChecklistItem(ctx context.Context, in *admin.AddTaskChecklistItemRequest) (*admin.AddTaskChecklistItemResponse, error) {
	out := new(admin.AddTaskChecklistItemResponse)
	if err := c.call(ctx, "POST", "/api/admin/task/checklist/add", in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) AddTaskComment(ctx context.Context, in *admin.AddTaskCommentRequest) (*admin.AddTaskCommentResponse, error) {
	out := new(admin.AddTaskCommentResponse)
	if err := c.call(ctx, "POST", "/api/admin/task/comment/add", in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) AddTechCardDevExpense(ctx context.Context, in *admin.AddTechCardDevExpenseRequest) (*admin.AddTechCardDevExpenseResponse, error) {
	out := new(admin.AddTechCardDevExpenseResponse)
	if err := c.call(ctx, "POST", "/api/admin/tech-card/dev-expense", in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) AdjustMaterialStock(ctx context.Context, in *admin.AdjustMaterialStockRequest) (*admin.AdjustMaterialStockResponse, error) {
	out := new(admin.AdjustMaterialStockResponse)
	if err := c.call(ctx, "POST", "/api/admin/inventory/adjust", in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) ArchiveAcctAccount(ctx context.Context, in *admin.ArchiveAcctAccountRequest) (*admin.ArchiveAcctAccountResponse, error) {
	out := new(admin.ArchiveAcctAccountResponse)
	if err := c.call(ctx, "POST", "/api/admin/accounting/accounts/archive", in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) ArchiveCollection(ctx context.Context, in *admin.ArchiveCollectionRequest) (*admin.ArchiveCollectionResponse, error) {
	out := new(admin.ArchiveCollectionResponse)
	if err := c.call(ctx, "POST", "/api/admin/dictionaries/collections/{id}/archive", in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) ArchiveColor(ctx context.Context, in *admin.ArchiveColorRequest) (*admin.ArchiveColorResponse, error) {
	out := new(admin.ArchiveColorResponse)
	if err := c.call(ctx, "POST", "/api/admin/dictionaries/colors/{code}/archive", in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) ArchiveColorwayByID(ctx context.Context, in *admin.ArchiveColorwayByIDRequest) (*admin.ArchiveColorwayByIDResponse, error) {
	out := new(admin.ArchiveColorwayByIDResponse)
	if err := c.call(ctx, "POST", "/api/admin/colorways/{colorway_id}/archive", in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) ArchiveEmployee(ctx context.Context, in *admin.ArchiveEmployeeRequest) (*admin.ArchiveEmployeeResponse, error) {
	out := new(admin.ArchiveEmployeeResponse)
	if err := c.call(ctx, "POST", "/api/admin/metrics/employees/archive", in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) ArchiveFiber(ctx context.Context, in *admin.ArchiveFiberRequest) (*admin.ArchiveFiberResponse, error) {
	out := new(admin.ArchiveFiberResponse)
	if err := c.call(ctx, "POST", "/api/admin/dictionaries/fibers/{code}/archive", in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) ArchiveMaterial(ctx context.Context, in *admin.ArchiveMaterialRequest) (*admin.ArchiveMaterialResponse, error) {
	out := new(admin.ArchiveMaterialResponse)
	if err := c.call(ctx, "POST", "/api/admin/materials/archive", in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) ArchiveOpexRecurring(ctx context.Context, in *admin.ArchiveOpexRecurringRequest) (*admin.ArchiveOpexRecurringResponse, error) {
	out := new(admin.ArchiveOpexRecurringResponse)
	if err := c.call(ctx, "POST", "/api/admin/metrics/opex/recurring/archive", in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) ArchiveTag(ctx context.Context, in *admin.ArchiveTagRequest) (*admin.ArchiveTagResponse, error) {
	out := new(admin.ArchiveTagResponse)
	if err := c.call(ctx, "POST", "/api/admin/dictionaries/tags/{id}/archive", in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) ArchiveTask(ctx context.Context, in *admin.ArchiveTaskRequest) (*admin.ArchiveTaskResponse, error) {
	out := new(admin.ArchiveTaskResponse)
	if err := c.call(ctx, "POST", "/api/admin/task/archive", in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) ArchiveVariant(ctx context.Context, in *admin.ArchiveVariantRequest) (*admin.ArchiveVariantResponse, error) {
	out := new(admin.ArchiveVariantResponse)
	if err := c.call(ctx, "POST", "/api/admin/variants/{variant_id}/archive", in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) AssignTechCardRole(ctx context.Context, in *admin.AssignTechCardRoleRequest) (*admin.AssignTechCardRoleResponse, error) {
	out := new(admin.AssignTechCardRoleResponse)
	if err := c.call(ctx, "POST", "/api/admin/tech-card/role/assign", in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) CancelOrder(ctx context.Context, in *admin.CancelOrderRequest) (*admin.CancelOrderResponse, error) {
	out := new(admin.CancelOrderResponse)
	if err := c.call(ctx, "POST", "/api/admin/orders/{order_uuid}/cancel", in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) CloneStyleForSeason(ctx context.Context, in *admin.CloneStyleForSeasonRequest) (*admin.CloneStyleForSeasonResponse, error) {
	out := new(admin.CloneStyleForSeasonResponse)
	if err := c.call(ctx, "POST", "/api/admin/styles/{source_style_id}/clone-for-season", in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) CloseAcctPeriod(ctx context.Context, in *admin.CloseAcctPeriodRequest) (*admin.CloseAcctPeriodResponse, error) {
	out := new(admin.CloseAcctPeriodResponse)
	if err := c.call(ctx, "POST", "/api/admin/accounting/periods/close", in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) CreateAccount(ctx context.Context, in *admin.CreateAccountRequest) (*admin.CreateAccountResponse, error) {
	out := new(admin.CreateAccountResponse)
	if err := c.call(ctx, "POST", "/api/admin/accounts", in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) CreateAcctAccount(ctx context.Context, in *admin.CreateAcctAccountRequest) (*admin.CreateAcctAccountResponse, error) {
	out := new(admin.CreateAcctAccountResponse)
	if err := c.call(ctx, "POST", "/api/admin/accounting/accounts", in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) CreateCollection(ctx context.Context, in *admin.CreateCollectionRequest) (*admin.CreateCollectionResponse, error) {
	out := new(admin.CreateCollectionResponse)
	if err := c.call(ctx, "POST", "/api/admin/dictionaries/collections", in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) CreateColor(ctx context.Context, in *admin.CreateColorRequest) (*admin.CreateColorResponse, error) {
	out := new(admin.CreateColorResponse)
	if err := c.call(ctx, "POST", "/api/admin/dictionaries/colors", in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) CreateColorway(ctx context.Context, in *admin.CreateColorwayRequest) (*admin.CreateColorwayResponse, error) {
	out := new(admin.CreateColorwayResponse)
	if err := c.call(ctx, "POST", "/api/admin/colorways", in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) CreateCustomOrder(ctx context.Context, in *admin.CreateCustomOrderRequest) (*admin.CreateCustomOrderResponse, error) {
	out := new(admin.CreateCustomOrderResponse)
	if err := c.call(ctx, "POST", "/api/admin/orders/custom", in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) CreateFiber(ctx context.Context, in *admin.CreateFiberRequest) (*admin.CreateFiberResponse, error) {
	out := new(admin.CreateFiberResponse)
	if err := c.call(ctx, "POST", "/api/admin/dictionaries/fibers", in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) CreateJournalEntry(ctx context.Context, in *admin.CreateJournalEntryRequest) (*admin.CreateJournalEntryResponse, error) {
	out := new(admin.CreateJournalEntryResponse)
	if err := c.call(ctx, "POST", "/api/admin/accounting/journal", in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) CreateMaterial(ctx context.Context, in *admin.CreateMaterialRequest) (*admin.CreateMaterialResponse, error) {
	out := new(admin.CreateMaterialResponse)
	if err := c.call(ctx, "POST", "/api/admin/materials", in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) CreateProductionRun(ctx context.Context, in *admin.CreateProductionRunRequest) (*admin.CreateProductionRunResponse, error) {
	out := new(admin.CreateProductionRunResponse)
	if err := c.call(ctx, "POST", "/api/admin/production-runs", in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) CreateTag(ctx context.Context, in *admin.CreateTagRequest) (*admin.CreateTagResponse, error) {
	out := new(admin.CreateTagResponse)
	if err := c.call(ctx, "POST", "/api/admin/dictionaries/tags", in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) CreateTechCard(ctx context.Context, in *admin.CreateTechCardRequest) (*admin.CreateTechCardResponse, error) {
	out := new(admin.CreateTechCardResponse)
	if err := c.call(ctx, "POST", "/api/admin/tech-card/add", in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) CreateVariant(ctx context.Context, in *admin.CreateVariantRequest) (*admin.CreateVariantResponse, error) {
	out := new(admin.CreateVariantResponse)
	if err := c.call(ctx, "POST", "/api/admin/colorways/{colorway_id}/variants", in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) DeleteAccount(ctx context.Context, in *admin.DeleteAccountRequest) (*admin.DeleteAccountResponse, error) {
	out := new(admin.DeleteAccountResponse)
	if err := c.call(ctx, "DELETE", "/api/admin/accounts/{username}", in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) DeleteArchiveById(ctx context.Context, in *admin.DeleteArchiveByIdRequest) (*admin.DeleteArchiveByIdResponse, error) {
	out := new(admin.DeleteArchiveByIdResponse)
	if err := c.call(ctx, "DELETE", "/api/admin/archive/{id}", in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) DeleteFitting(ctx context.Context, in *admin.DeleteFittingRequest) (*admin.DeleteFittingResponse, error) {
	out := new(admin.DeleteFittingResponse)
	if err := c.call(ctx, "DELETE", "/api/admin/fitting/{id}", in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) DeleteFittingChangeRequest(ctx context.Context, in *admin.DeleteFittingChangeRequestRequest) (*admin.DeleteFittingChangeRequestResponse, error) {
	out := new(admin.DeleteFittingChangeRequestResponse)
	if err := c.call(ctx, "DELETE", "/api/admin/fitting/change-request/{id}", in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) DeleteFromBucket(ctx context.Context, in *admin.DeleteFromBucketRequest) (*admin.DeleteFromBucketResponse, error) {
	out := new(admin.DeleteFromBucketResponse)
	if err := c.call(ctx, "DELETE", "/api/admin/content", in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) DeleteFulfillmentChecklistItem(ctx context.Context, in *admin.DeleteFulfillmentChecklistItemRequest) (*admin.DeleteFulfillmentChecklistItemResponse, error) {
	out := new(admin.DeleteFulfillmentChecklistItemResponse)
	if err := c.call(ctx, "DELETE", "/api/admin/fulfillment/checklist/{id}", in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) DeleteModel(ctx context.Context, in *admin.DeleteModelRequest) (*admin.DeleteModelResponse, error) {
	out := new(admin.DeleteModelResponse)
	if err := c.call(ctx, "DELETE", "/api/admin/model/{id}", in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) DeleteOpexLine(ctx context.Context, in *admin.DeleteOpexLineRequest) (*admin.DeleteOpexLineResponse, error) {
	out := new(admin.DeleteOpexLineResponse)
	if err := c.call(ctx, "POST", "/api/admin/metrics/opex/lines/delete", in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) DeleteOrderReview(ctx context.Context, in *admin.DeleteOrderReviewRequest) (*admin.DeleteOrderReviewResponse, error) {
	out := new(admin.DeleteOrderReviewResponse)
	if err := c.call(ctx, "DELETE", "/api/admin/review/{order_id}", in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) DeleteProductionRun(ctx context.Context, in *admin.DeleteProductionRunRequest) (*admin.DeleteProductionRunResponse, error) {
	out := new(admin.DeleteProductionRunResponse)
	if err := c.call(ctx, "DELETE", "/api/admin/production-runs/{id}", in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) DeletePromoCode(ctx context.Context, in *admin.DeletePromoCodeRequest) (*admin.DeletePromoCodeResponse, error) {
	out := new(admin.DeletePromoCodeResponse)
	if err := c.call(ctx, "DELETE", "/api/admin/promo/{code}/delete", in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) DeleteSample(ctx context.Context, in *admin.DeleteSampleRequest) (*admin.DeleteSampleResponse, error) {
	out := new(admin.DeleteSampleResponse)
	if err := c.call(ctx, "DELETE", "/api/admin/sample/{id}", in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) DeleteSampleSubstitution(ctx context.Context, in *admin.DeleteSampleSubstitutionRequest) (*admin.DeleteSampleSubstitutionResponse, error) {
	out := new(admin.DeleteSampleSubstitutionResponse)
	if err := c.call(ctx, "DELETE", "/api/admin/sample/substitution/{id}", in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) DeleteShipmentCarrier(ctx context.Context, in *admin.DeleteShipmentCarrierRequest) (*admin.DeleteShipmentCarrierResponse, error) {
	out := new(admin.DeleteShipmentCarrierResponse)
	if err := c.call(ctx, "DELETE", "/api/admin/settings/shipment-carrier/{id}", in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) DeleteTask(ctx context.Context, in *admin.DeleteTaskRequest) (*admin.DeleteTaskResponse, error) {
	out := new(admin.DeleteTaskResponse)
	if err := c.call(ctx, "DELETE", "/api/admin/task/{id}", in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) DeleteTaskChecklistItem(ctx context.Context, in *admin.DeleteTaskChecklistItemRequest) (*admin.DeleteTaskChecklistItemResponse, error) {
	out := new(admin.DeleteTaskChecklistItemResponse)
	if err := c.call(ctx, "DELETE", "/api/admin/task/checklist/{id}", in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) DeleteTechCard(ctx context.Context, in *admin.DeleteTechCardRequest) (*admin.DeleteTechCardResponse, error) {
	out := new(admin.DeleteTechCardResponse)
	if err := c.call(ctx, "DELETE", "/api/admin/tech-card/{id}", in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) DeleteTechCardDevExpense(ctx context.Context, in *admin.DeleteTechCardDevExpenseRequest) (*admin.DeleteTechCardDevExpenseResponse, error) {
	out := new(admin.DeleteTechCardDevExpenseResponse)
	if err := c.call(ctx, "DELETE", "/api/admin/tech-card/dev-expense/{id}", in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) DeliveredOrder(ctx context.Context, in *admin.DeliveredOrderRequest) (*admin.DeliveredOrderResponse, error) {
	out := new(admin.DeliveredOrderResponse)
	if err := c.call(ctx, "POST", "/api/admin/orders/{order_uuid}/delivered", in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) DisablePromoCode(ctx context.Context, in *admin.DisablePromoCodeRequest) (*admin.DisablePromoCodeResponse, error) {
	out := new(admin.DisablePromoCodeResponse)
	if err := c.call(ctx, "POST", "/api/admin/promo/{code}/disable", in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) GenerateHackerInvite(ctx context.Context, in *admin.GenerateHackerInviteRequest) (*admin.GenerateHackerInviteResponse, error) {
	out := new(admin.GenerateHackerInviteResponse)
	if err := c.call(ctx, "POST", "/api/admin/hacker/invite", in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) GenerateShippingLabel(ctx context.Context, in *admin.GenerateShippingLabelRequest) (*admin.GenerateShippingLabelResponse, error) {
	out := new(admin.GenerateShippingLabelResponse)
	if err := c.call(ctx, "POST", "/api/admin/fulfillment/label", in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) GenerateTechCardOperations(ctx context.Context, in *admin.GenerateTechCardOperationsRequest) (*admin.GenerateTechCardOperationsResponse, error) {
	out := new(admin.GenerateTechCardOperationsResponse)
	if err := c.call(ctx, "POST", "/api/admin/tech-card/operations/generate", in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) GetAccountLedger(ctx context.Context, in *admin.GetAccountLedgerRequest) (*admin.GetAccountLedgerResponse, error) {
	out := new(admin.GetAccountLedgerResponse)
	if err := c.call(ctx, "GET", "/api/admin/accounting/reports/ledger/{code}", in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) GetAcctReconciliation(ctx context.Context, in *admin.GetAcctReconciliationRequest) (*admin.GetAcctReconciliationResponse, error) {
	out := new(admin.GetAcctReconciliationResponse)
	if err := c.call(ctx, "GET", "/api/admin/accounting/reports/reconciliation", in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) GetAlertSettings(ctx context.Context, in *admin.GetAlertSettingsRequest) (*admin.GetAlertSettingsResponse, error) {
	out := new(admin.GetAlertSettingsResponse)
	if err := c.call(ctx, "GET", "/api/admin/dashboard/alert-settings", in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) GetArchiveByID(ctx context.Context, in *admin.GetArchiveByIDRequest) (*admin.GetArchiveByIDResponse, error) {
	out := new(admin.GetArchiveByIDResponse)
	if err := c.call(ctx, "GET", "/api/admin/archive/{id}", in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) GetArchivesPaged(ctx context.Context, in *admin.GetArchivesPagedRequest) (*admin.GetArchivesPagedResponse, error) {
	out := new(admin.GetArchivesPagedResponse)
	if err := c.call(ctx, "GET", "/api/admin/archive/paged", in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) GetBackgroundHeroColor(ctx context.Context, in *admin.GetBackgroundHeroColorRequest) (*admin.GetBackgroundHeroColorResponse, error) {
	out := new(admin.GetBackgroundHeroColorResponse)
	if err := c.call(ctx, "GET", "/api/admin/settings/background-hero-color", in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) GetBalanceSheet(ctx context.Context, in *admin.GetBalanceSheetRequest) (*admin.GetBalanceSheetResponse, error) {
	out := new(admin.GetBalanceSheetResponse)
	if err := c.call(ctx, "GET", "/api/admin/accounting/reports/balance-sheet", in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) GetChannelRoasSettled(ctx context.Context, in *admin.GetChannelRoasSettledRequest) (*admin.GetChannelRoasSettledResponse, error) {
	out := new(admin.GetChannelRoasSettledResponse)
	if err := c.call(ctx, "GET", "/api/admin/metrics/channel-roas-settled", in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) GetColorwayByID(ctx context.Context, in *admin.GetColorwayByIDRequest) (*admin.GetColorwayByIDResponse, error) {
	out := new(admin.GetColorwayByIDResponse)
	if err := c.call(ctx, "GET", "/api/admin/colorways/{colorway_id}", in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) GetColorwayCustoms(ctx context.Context, in *admin.GetColorwayCustomsRequest) (*admin.GetColorwayCustomsResponse, error) {
	out := new(admin.GetColorwayCustomsResponse)
	if err := c.call(ctx, "GET", "/api/admin/colorways/{colorway_id}/customs", in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) GetColorwaysPaged(ctx context.Context, in *admin.GetColorwaysPagedRequest) (*admin.GetColorwaysPagedResponse, error) {
	out := new(admin.GetColorwaysPagedResponse)
	if err := c.call(ctx, "GET", "/api/admin/colorways/paged", in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) GetCostingFxRates(ctx context.Context, in *admin.GetCostingFxRatesRequest) (*admin.GetCostingFxRatesResponse, error) {
	out := new(admin.GetCostingFxRatesResponse)
	if err := c.call(ctx, "GET", "/api/admin/costing/fx-rates", in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) GetCurrentAccount(ctx context.Context, in *admin.GetCurrentAccountRequest) (*admin.GetCurrentAccountResponse, error) {
	out := new(admin.GetCurrentAccountResponse)
	if err := c.call(ctx, "GET", "/api/admin/accounts/me", in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) GetDashboard(ctx context.Context, in *admin.GetDashboardRequest) (*admin.GetDashboardResponse, error) {
	out := new(admin.GetDashboardResponse)
	if err := c.call(ctx, "GET", "/api/admin/dashboard", in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) GetDictionary(ctx context.Context, in *admin.GetDictionaryRequest) (*admin.GetDictionaryResponse, error) {
	out := new(admin.GetDictionaryResponse)
	if err := c.call(ctx, "GET", "/api/admin/dictionary", in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) GetFitting(ctx context.Context, in *admin.GetFittingRequest) (*admin.GetFittingResponse, error) {
	out := new(admin.GetFittingResponse)
	if err := c.call(ctx, "GET", "/api/admin/fitting/{id}", in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) GetFulfillmentBoard(ctx context.Context, in *admin.GetFulfillmentBoardRequest) (*admin.GetFulfillmentBoardResponse, error) {
	out := new(admin.GetFulfillmentBoardResponse)
	if err := c.call(ctx, "GET", "/api/admin/fulfillment/board", in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) GetFulfillmentCard(ctx context.Context, in *admin.GetFulfillmentCardRequest) (*admin.GetFulfillmentCardResponse, error) {
	out := new(admin.GetFulfillmentCardResponse)
	if err := c.call(ctx, "GET", "/api/admin/fulfillment/card/{order_uuid}", in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) GetJournalEntry(ctx context.Context, in *admin.GetJournalEntryRequest) (*admin.GetJournalEntryResponse, error) {
	out := new(admin.GetJournalEntryResponse)
	if err := c.call(ctx, "GET", "/api/admin/accounting/journal/{id}", in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) GetMaterial(ctx context.Context, in *admin.GetMaterialRequest) (*admin.GetMaterialResponse, error) {
	out := new(admin.GetMaterialResponse)
	if err := c.call(ctx, "GET", "/api/admin/materials/{id}", in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) GetMaterialStock(ctx context.Context, in *admin.GetMaterialStockRequest) (*admin.GetMaterialStockResponse, error) {
	out := new(admin.GetMaterialStockResponse)
	if err := c.call(ctx, "GET", "/api/admin/inventory/{material_id}", in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) GetMember(ctx context.Context, in *admin.GetMemberRequest) (*admin.GetMemberResponse, error) {
	out := new(admin.GetMemberResponse)
	if err := c.call(ctx, "GET", "/api/admin/members/{user_id}", in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) GetMetrics(ctx context.Context, in *admin.GetMetricsRequest) (*admin.GetMetricsResponse, error) {
	out := new(admin.GetMetricsResponse)
	if err := c.call(ctx, "GET", "/api/admin/metrics", in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) GetModel(ctx context.Context, in *admin.GetModelRequest) (*admin.GetModelResponse, error) {
	out := new(admin.GetModelResponse)
	if err := c.call(ctx, "GET", "/api/admin/model/{id}", in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) GetOrderByUUID(ctx context.Context, in *admin.GetOrderByUUIDRequest) (*admin.GetOrderByUUIDResponse, error) {
	out := new(admin.GetOrderByUUIDResponse)
	if err := c.call(ctx, "GET", "/api/admin/order/{order_uuid}", in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) GetOrderPackingSpec(ctx context.Context, in *admin.GetOrderPackingSpecRequest) (*admin.GetOrderPackingSpecResponse, error) {
	out := new(admin.GetOrderPackingSpecResponse)
	if err := c.call(ctx, "GET", "/api/admin/fulfillment/{order_uuid}/packing-spec", in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) GetOrderReviewsPaged(ctx context.Context, in *admin.GetOrderReviewsPagedRequest) (*admin.GetOrderReviewsPagedResponse, error) {
	out := new(admin.GetOrderReviewsPagedResponse)
	if err := c.call(ctx, "GET", "/api/admin/reviews/paged", in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) GetOssReturn(ctx context.Context, in *admin.GetOssReturnRequest) (*admin.GetOssReturnResponse, error) {
	out := new(admin.GetOssReturnResponse)
	if err := c.call(ctx, "GET", "/api/admin/accounting/reports/oss-return", in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) GetProductReviewsPaged(ctx context.Context, in *admin.GetProductReviewsPagedRequest) (*admin.GetProductReviewsPagedResponse, error) {
	out := new(admin.GetProductReviewsPagedResponse)
	if err := c.call(ctx, "GET", "/api/admin/product/{product_id}/reviews", in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) GetProductionRun(ctx context.Context, in *admin.GetProductionRunRequest) (*admin.GetProductionRunResponse, error) {
	out := new(admin.GetProductionRunResponse)
	if err := c.call(ctx, "GET", "/api/admin/production-runs/{id}", in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) GetProductionRunMaterialPlan(ctx context.Context, in *admin.GetProductionRunMaterialPlanRequest) (*admin.GetProductionRunMaterialPlanResponse, error) {
	out := new(admin.GetProductionRunMaterialPlanResponse)
	if err := c.call(ctx, "GET", "/api/admin/production-runs/{run_id}/material-plan", in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) GetProfitLossStatement(ctx context.Context, in *admin.GetProfitLossStatementRequest) (*admin.GetProfitLossStatementResponse, error) {
	out := new(admin.GetProfitLossStatementResponse)
	if err := c.call(ctx, "GET", "/api/admin/accounting/reports/profit-loss", in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) GetSample(ctx context.Context, in *admin.GetSampleRequest) (*admin.GetSampleResponse, error) {
	out := new(admin.GetSampleResponse)
	if err := c.call(ctx, "GET", "/api/admin/sample/{id}", in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) GetShippingOptions(ctx context.Context, in *admin.GetShippingOptionsRequest) (*admin.GetShippingOptionsResponse, error) {
	out := new(admin.GetShippingOptionsResponse)
	if err := c.call(ctx, "POST", "/api/admin/fulfillment/label/options", in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) GetStyleCostEstimate(ctx context.Context, in *admin.GetStyleCostEstimateRequest) (*admin.GetStyleCostEstimateResponse, error) {
	out := new(admin.GetStyleCostEstimateResponse)
	if err := c.call(ctx, "GET", "/api/admin/metrics/style-cost-estimate", in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) GetStyleCutList(ctx context.Context, in *admin.GetStyleCutListRequest) (*admin.GetStyleCutListResponse, error) {
	out := new(admin.GetStyleCutListResponse)
	if err := c.call(ctx, "GET", "/api/admin/styles/{tech_card_id}/cut-list", in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) GetStyleEconomics(ctx context.Context, in *admin.GetStyleEconomicsRequest) (*admin.GetStyleEconomicsResponse, error) {
	out := new(admin.GetStyleEconomicsResponse)
	if err := c.call(ctx, "GET", "/api/admin/metrics/style-economics", in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) GetStylePipeline(ctx context.Context, in *admin.GetStylePipelineRequest) (*admin.GetStylePipelineResponse, error) {
	out := new(admin.GetStylePipelineResponse)
	if err := c.call(ctx, "GET", "/api/admin/tech-card/pipeline", in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) GetStyleSizeChart(ctx context.Context, in *admin.GetStyleSizeChartRequest) (*admin.GetStyleSizeChartResponse, error) {
	out := new(admin.GetStyleSizeChartResponse)
	if err := c.call(ctx, "GET", "/api/admin/styles/{style_id}/size-chart", in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) GetSupportTicketByCaseNumber(ctx context.Context, in *admin.GetSupportTicketByCaseNumberRequest) (*admin.GetSupportTicketByCaseNumberResponse, error) {
	out := new(admin.GetSupportTicketByCaseNumberResponse)
	if err := c.call(ctx, "GET", "/api/admin/support/tickets/case/{case_number}", in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) GetSupportTicketById(ctx context.Context, in *admin.GetSupportTicketByIdRequest) (*admin.GetSupportTicketByIdResponse, error) {
	out := new(admin.GetSupportTicketByIdResponse)
	if err := c.call(ctx, "GET", "/api/admin/support/tickets/{id}", in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) GetSupportTicketsPaged(ctx context.Context, in *admin.GetSupportTicketsPagedRequest) (*admin.GetSupportTicketsPagedResponse, error) {
	out := new(admin.GetSupportTicketsPagedResponse)
	if err := c.call(ctx, "GET", "/api/admin/support/tickets/paged", in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) GetTask(ctx context.Context, in *admin.GetTaskRequest) (*admin.GetTaskResponse, error) {
	out := new(admin.GetTaskResponse)
	if err := c.call(ctx, "GET", "/api/admin/task/{id}", in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) GetTechCard(ctx context.Context, in *admin.GetTechCardRequest) (*admin.GetTechCardResponse, error) {
	out := new(admin.GetTechCardResponse)
	if err := c.call(ctx, "GET", "/api/admin/tech-card/{id}", in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) GetTechCardRelease(ctx context.Context, in *admin.GetTechCardReleaseRequest) (*admin.GetTechCardReleaseResponse, error) {
	out := new(admin.GetTechCardReleaseResponse)
	if err := c.call(ctx, "GET", "/api/admin/tech-card/release/{id}", in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) GetTierAuditLog(ctx context.Context, in *admin.GetTierAuditLogRequest) (*admin.GetTierAuditLogResponse, error) {
	out := new(admin.GetTierAuditLogResponse)
	if err := c.call(ctx, "GET", "/api/admin/tier-audit", in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) GetTierConfig(ctx context.Context, in *admin.GetTierConfigRequest) (*admin.GetTierConfigResponse, error) {
	out := new(admin.GetTierConfigResponse)
	if err := c.call(ctx, "GET", "/api/admin/tier-config", in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) GetTierHistory(ctx context.Context, in *admin.GetTierHistoryRequest) (*admin.GetTierHistoryResponse, error) {
	out := new(admin.GetTierHistoryResponse)
	if err := c.call(ctx, "GET", "/api/admin/members/{user_id}/tier-history", in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) GetTrialBalance(ctx context.Context, in *admin.GetTrialBalanceRequest) (*admin.GetTrialBalanceResponse, error) {
	out := new(admin.GetTrialBalanceResponse)
	if err := c.call(ctx, "GET", "/api/admin/accounting/reports/trial-balance", in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) GetVatRates(ctx context.Context, in *admin.GetVatRatesRequest) (*admin.GetVatRatesResponse, error) {
	out := new(admin.GetVatRatesResponse)
	if err := c.call(ctx, "GET", "/api/admin/vat-rates", in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) GetVatReturnPL(ctx context.Context, in *admin.GetVatReturnPLRequest) (*admin.GetVatReturnPLResponse, error) {
	out := new(admin.GetVatReturnPLResponse)
	if err := c.call(ctx, "GET", "/api/admin/accounting/reports/vat-return", in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) HardEraseMember(ctx context.Context, in *admin.HardEraseMemberRequest) (*admin.HardEraseMemberResponse, error) {
	out := new(admin.HardEraseMemberResponse)
	if err := c.call(ctx, "POST", "/api/admin/members/{user_id}/erase", in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) IssueMaterialStock(ctx context.Context, in *admin.IssueMaterialStockRequest) (*admin.IssueMaterialStockResponse, error) {
	out := new(admin.IssueMaterialStockResponse)
	if err := c.call(ctx, "POST", "/api/admin/inventory/issue", in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) ListAccountSections(ctx context.Context, in *admin.ListAccountSectionsRequest) (*admin.ListAccountSectionsResponse, error) {
	out := new(admin.ListAccountSectionsResponse)
	if err := c.call(ctx, "GET", "/api/admin/accounts/sections", in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) ListAccounts(ctx context.Context, in *admin.ListAccountsRequest) (*admin.ListAccountsResponse, error) {
	out := new(admin.ListAccountsResponse)
	if err := c.call(ctx, "GET", "/api/admin/accounts", in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) ListAcctAccounts(ctx context.Context, in *admin.ListAcctAccountsRequest) (*admin.ListAcctAccountsResponse, error) {
	out := new(admin.ListAcctAccountsResponse)
	if err := c.call(ctx, "GET", "/api/admin/accounting/accounts", in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) ListAcctEventsNeedingReview(ctx context.Context, in *admin.ListAcctEventsNeedingReviewRequest) (*admin.ListAcctEventsNeedingReviewResponse, error) {
	out := new(admin.ListAcctEventsNeedingReviewResponse)
	if err := c.call(ctx, "GET", "/api/admin/accounting/events/needs-review", in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) ListAcctPeriods(ctx context.Context, in *admin.ListAcctPeriodsRequest) (*admin.ListAcctPeriodsResponse, error) {
	out := new(admin.ListAcctPeriodsResponse)
	if err := c.call(ctx, "GET", "/api/admin/accounting/periods", in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) ListAdmins(ctx context.Context, in *admin.ListAdminsRequest) (*admin.ListAdminsResponse, error) {
	out := new(admin.ListAdminsResponse)
	if err := c.call(ctx, "GET", "/api/admin/admins/pick", in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) ListCollections(ctx context.Context, in *admin.ListCollectionsRequest) (*admin.ListCollectionsResponse, error) {
	out := new(admin.ListCollectionsResponse)
	if err := c.call(ctx, "GET", "/api/admin/dictionaries/collections", in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) ListColors(ctx context.Context, in *admin.ListColorsRequest) (*admin.ListColorsResponse, error) {
	out := new(admin.ListColorsResponse)
	if err := c.call(ctx, "GET", "/api/admin/dictionaries/colors", in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) ListCountries(ctx context.Context, in *admin.ListCountriesRequest) (*admin.ListCountriesResponse, error) {
	out := new(admin.ListCountriesResponse)
	if err := c.call(ctx, "GET", "/api/admin/dictionaries/countries", in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) ListEmployees(ctx context.Context, in *admin.ListEmployeesRequest) (*admin.ListEmployeesResponse, error) {
	out := new(admin.ListEmployeesResponse)
	if err := c.call(ctx, "POST", "/api/admin/metrics/employees/list", in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) ListFittings(ctx context.Context, in *admin.ListFittingsRequest) (*admin.ListFittingsResponse, error) {
	out := new(admin.ListFittingsResponse)
	if err := c.call(ctx, "GET", "/api/admin/fitting/list", in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) ListHackerAccounts(ctx context.Context, in *admin.ListHackerAccountsRequest) (*admin.ListHackerAccountsResponse, error) {
	out := new(admin.ListHackerAccountsResponse)
	if err := c.call(ctx, "GET", "/api/admin/hacker/accounts", in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) ListHackerInvites(ctx context.Context, in *admin.ListHackerInvitesRequest) (*admin.ListHackerInvitesResponse, error) {
	out := new(admin.ListHackerInvitesResponse)
	if err := c.call(ctx, "GET", "/api/admin/hacker/invites", in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) ListJournalEntries(ctx context.Context, in *admin.ListJournalEntriesRequest) (*admin.ListJournalEntriesResponse, error) {
	out := new(admin.ListJournalEntriesResponse)
	if err := c.call(ctx, "GET", "/api/admin/accounting/journal", in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) ListMaterialLots(ctx context.Context, in *admin.ListMaterialLotsRequest) (*admin.ListMaterialLotsResponse, error) {
	out := new(admin.ListMaterialLotsResponse)
	if err := c.call(ctx, "GET", "/api/admin/inventory/{material_id}/lots", in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) ListMaterialMovements(ctx context.Context, in *admin.ListMaterialMovementsRequest) (*admin.ListMaterialMovementsResponse, error) {
	out := new(admin.ListMaterialMovementsResponse)
	if err := c.call(ctx, "GET", "/api/admin/inventory/movements", in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) ListMaterialPrices(ctx context.Context, in *admin.ListMaterialPricesRequest) (*admin.ListMaterialPricesResponse, error) {
	out := new(admin.ListMaterialPricesResponse)
	if err := c.call(ctx, "GET", "/api/admin/materials/{material_id}/prices", in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) ListMaterialStock(ctx context.Context, in *admin.ListMaterialStockRequest) (*admin.ListMaterialStockResponse, error) {
	out := new(admin.ListMaterialStockResponse)
	if err := c.call(ctx, "GET", "/api/admin/inventory", in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) ListMaterials(ctx context.Context, in *admin.ListMaterialsRequest) (*admin.ListMaterialsResponse, error) {
	out := new(admin.ListMaterialsResponse)
	if err := c.call(ctx, "GET", "/api/admin/materials", in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) ListMembers(ctx context.Context, in *admin.ListMembersRequest) (*admin.ListMembersResponse, error) {
	out := new(admin.ListMembersResponse)
	if err := c.call(ctx, "GET", "/api/admin/members", in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) ListModels(ctx context.Context, in *admin.ListModelsRequest) (*admin.ListModelsResponse, error) {
	out := new(admin.ListModelsResponse)
	if err := c.call(ctx, "GET", "/api/admin/model/list", in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) ListObjectsPaged(ctx context.Context, in *admin.ListObjectsPagedRequest) (*admin.ListObjectsPagedResponse, error) {
	out := new(admin.ListObjectsPagedResponse)
	if err := c.call(ctx, "GET", "/api/admin/content", in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) ListOpenFittingChangeRequests(ctx context.Context, in *admin.ListOpenFittingChangeRequestsRequest) (*admin.ListOpenFittingChangeRequestsResponse, error) {
	out := new(admin.ListOpenFittingChangeRequestsResponse)
	if err := c.call(ctx, "GET", "/api/admin/fitting/change-request/open", in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) ListOpexLines(ctx context.Context, in *admin.ListOpexLinesRequest) (*admin.ListOpexLinesResponse, error) {
	out := new(admin.ListOpexLinesResponse)
	if err := c.call(ctx, "POST", "/api/admin/metrics/opex/lines/list", in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) ListOpexRecurring(ctx context.Context, in *admin.ListOpexRecurringRequest) (*admin.ListOpexRecurringResponse, error) {
	out := new(admin.ListOpexRecurringResponse)
	if err := c.call(ctx, "POST", "/api/admin/metrics/opex/recurring/list", in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) ListOrders(ctx context.Context, in *admin.ListOrdersRequest) (*admin.ListOrdersResponse, error) {
	out := new(admin.ListOrdersResponse)
	if err := c.call(ctx, "POST", "/api/admin/orders/list", in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) ListPackagingBom(ctx context.Context, in *admin.ListPackagingBomRequest) (*admin.ListPackagingBomResponse, error) {
	out := new(admin.ListPackagingBomResponse)
	if err := c.call(ctx, "GET", "/api/admin/inventory/packaging-bom", in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) ListPackagingRecipe(ctx context.Context, in *admin.ListPackagingRecipeRequest) (*admin.ListPackagingRecipeResponse, error) {
	out := new(admin.ListPackagingRecipeResponse)
	if err := c.call(ctx, "GET", "/api/admin/inventory/packaging-recipe", in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) ListProductionRuns(ctx context.Context, in *admin.ListProductionRunsRequest) (*admin.ListProductionRunsResponse, error) {
	out := new(admin.ListProductionRunsResponse)
	if err := c.call(ctx, "GET", "/api/admin/production-runs", in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) ListPromos(ctx context.Context, in *admin.ListPromosRequest) (*admin.ListPromosResponse, error) {
	out := new(admin.ListPromosResponse)
	if err := c.call(ctx, "GET", "/api/admin/promo/list", in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) ListSampleSubstitutions(ctx context.Context, in *admin.ListSampleSubstitutionsRequest) (*admin.ListSampleSubstitutionsResponse, error) {
	out := new(admin.ListSampleSubstitutionsResponse)
	if err := c.call(ctx, "GET", "/api/admin/sample/{sample_id}/substitutions", in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) ListSamples(ctx context.Context, in *admin.ListSamplesRequest) (*admin.ListSamplesResponse, error) {
	out := new(admin.ListSamplesResponse)
	if err := c.call(ctx, "GET", "/api/admin/sample/list", in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) ListStockChangeHistory(ctx context.Context, in *admin.ListStockChangeHistoryRequest) (*admin.ListStockChangeHistoryResponse, error) {
	out := new(admin.ListStockChangeHistoryResponse)
	if err := c.call(ctx, "GET", "/api/admin/stock-change-history", in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) ListStockChanges(ctx context.Context, in *admin.ListStockChangesRequest) (*admin.ListStockChangesResponse, error) {
	out := new(admin.ListStockChangesResponse)
	if err := c.call(ctx, "GET", "/api/admin/stock-changes", in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) ListStyleAssembly(ctx context.Context, in *admin.ListStyleAssemblyRequest) (*admin.ListStyleAssemblyResponse, error) {
	out := new(admin.ListStyleAssemblyResponse)
	if err := c.call(ctx, "GET", "/api/admin/tech-card/{style_id}/style-assembly", in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) ListTags(ctx context.Context, in *admin.ListTagsRequest) (*admin.ListTagsResponse, error) {
	out := new(admin.ListTagsResponse)
	if err := c.call(ctx, "GET", "/api/admin/dictionaries/tags", in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) ListTaskComments(ctx context.Context, in *admin.ListTaskCommentsRequest) (*admin.ListTaskCommentsResponse, error) {
	out := new(admin.ListTaskCommentsResponse)
	if err := c.call(ctx, "GET", "/api/admin/task/{task_id}/comments", in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) ListTasks(ctx context.Context, in *admin.ListTasksRequest) (*admin.ListTasksResponse, error) {
	out := new(admin.ListTasksResponse)
	if err := c.call(ctx, "GET", "/api/admin/task/list", in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) ListTechCardDevExpenses(ctx context.Context, in *admin.ListTechCardDevExpensesRequest) (*admin.ListTechCardDevExpensesResponse, error) {
	out := new(admin.ListTechCardDevExpensesResponse)
	if err := c.call(ctx, "GET", "/api/admin/tech-card/{tech_card_id}/dev-expenses", in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) ListTechCardReleases(ctx context.Context, in *admin.ListTechCardReleasesRequest) (*admin.ListTechCardReleasesResponse, error) {
	out := new(admin.ListTechCardReleasesResponse)
	if err := c.call(ctx, "GET", "/api/admin/tech-card/{tech_card_id}/releases", in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) ListTechCardRoleAssignments(ctx context.Context, in *admin.ListTechCardRoleAssignmentsRequest) (*admin.ListTechCardRoleAssignmentsResponse, error) {
	out := new(admin.ListTechCardRoleAssignmentsResponse)
	if err := c.call(ctx, "GET", "/api/admin/tech-card/{tech_card_id}/roles", in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) ListTechCards(ctx context.Context, in *admin.ListTechCardsRequest) (*admin.ListTechCardsResponse, error) {
	out := new(admin.ListTechCardsResponse)
	if err := c.call(ctx, "GET", "/api/admin/tech-card/list", in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) MarkFulfillmentDelivered(ctx context.Context, in *admin.MarkFulfillmentDeliveredRequest) (*admin.MarkFulfillmentDeliveredResponse, error) {
	out := new(admin.MarkFulfillmentDeliveredResponse)
	if err := c.call(ctx, "POST", "/api/admin/fulfillment/deliver", in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) MoveTask(ctx context.Context, in *admin.MoveTaskRequest) (*admin.MoveTaskResponse, error) {
	out := new(admin.MoveTaskResponse)
	if err := c.call(ctx, "POST", "/api/admin/task/move", in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) OverrideTier(ctx context.Context, in *admin.OverrideTierRequest) (*admin.OverrideTierResponse, error) {
	out := new(admin.OverrideTierResponse)
	if err := c.call(ctx, "POST", "/api/admin/members/{user_id}/tier", in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) PrepareShippingLabel(ctx context.Context, in *admin.PrepareShippingLabelRequest) (*admin.PrepareShippingLabelResponse, error) {
	out := new(admin.PrepareShippingLabelResponse)
	if err := c.call(ctx, "GET", "/api/admin/fulfillment/label/{order_uuid}", in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) PublishColorway(ctx context.Context, in *admin.PublishColorwayRequest) (*admin.PublishColorwayResponse, error) {
	out := new(admin.PublishColorwayResponse)
	if err := c.call(ctx, "POST", "/api/admin/colorways/{colorway_id}/publish", in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) ReceiveMaterialStock(ctx context.Context, in *admin.ReceiveMaterialStockRequest) (*admin.ReceiveMaterialStockResponse, error) {
	out := new(admin.ReceiveMaterialStockResponse)
	if err := c.call(ctx, "POST", "/api/admin/inventory/receive", in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) ReceiveProductionRun(ctx context.Context, in *admin.ReceiveProductionRunRequest) (*admin.ReceiveProductionRunResponse, error) {
	out := new(admin.ReceiveProductionRunResponse)
	if err := c.call(ctx, "POST", "/api/admin/production-runs/{run_id}/receive", in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) RefundOrder(ctx context.Context, in *admin.RefundOrderRequest) (*admin.RefundOrderResponse, error) {
	out := new(admin.RefundOrderResponse)
	if err := c.call(ctx, "POST", "/api/admin/orders/{order_uuid}/refund", in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) RelinkDraftColorway(ctx context.Context, in *admin.RelinkDraftColorwayRequest) (*admin.RelinkDraftColorwayResponse, error) {
	out := new(admin.RelinkDraftColorwayResponse)
	if err := c.call(ctx, "POST", "/api/admin/colorways/{colorway_id}/relink", in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) RemoveTechCardRoleAssignment(ctx context.Context, in *admin.RemoveTechCardRoleAssignmentRequest) (*admin.RemoveTechCardRoleAssignmentResponse, error) {
	out := new(admin.RemoveTechCardRoleAssignmentResponse)
	if err := c.call(ctx, "POST", "/api/admin/tech-card/role/remove", in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) ReopenAcctPeriod(ctx context.Context, in *admin.ReopenAcctPeriodRequest) (*admin.ReopenAcctPeriodResponse, error) {
	out := new(admin.ReopenAcctPeriodResponse)
	if err := c.call(ctx, "POST", "/api/admin/accounting/periods/reopen", in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) ReprocessAcctEvent(ctx context.Context, in *admin.ReprocessAcctEventRequest) (*admin.ReprocessAcctEventResponse, error) {
	out := new(admin.ReprocessAcctEventResponse)
	if err := c.call(ctx, "POST", "/api/admin/accounting/events/reprocess", in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) ResetAccountPassword(ctx context.Context, in *admin.ResetAccountPasswordRequest) (*admin.ResetAccountPasswordResponse, error) {
	out := new(admin.ResetAccountPasswordResponse)
	if err := c.call(ctx, "PUT", "/api/admin/accounts/{username}/password", in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) ResolveAcctEvent(ctx context.Context, in *admin.ResolveAcctEventRequest) (*admin.ResolveAcctEventResponse, error) {
	out := new(admin.ResolveAcctEventResponse)
	if err := c.call(ctx, "POST", "/api/admin/accounting/events/resolve", in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) ReverseJournalEntry(ctx context.Context, in *admin.ReverseJournalEntryRequest) (*admin.ReverseJournalEntryResponse, error) {
	out := new(admin.ReverseJournalEntryResponse)
	if err := c.call(ctx, "POST", "/api/admin/accounting/journal/reverse", in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) RevokeHackerInvite(ctx context.Context, in *admin.RevokeHackerInviteRequest) (*admin.RevokeHackerInviteResponse, error) {
	out := new(admin.RevokeHackerInviteResponse)
	if err := c.call(ctx, "POST", "/api/admin/hacker/invite/{invite_id}/revoke", in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) RevokeHackerStatus(ctx context.Context, in *admin.RevokeHackerStatusRequest) (*admin.RevokeHackerStatusResponse, error) {
	out := new(admin.RevokeHackerStatusResponse)
	if err := c.call(ctx, "POST", "/api/admin/hacker/accounts/{user_id}/revoke", in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) RunTierBackfill(ctx context.Context, in *admin.RunTierBackfillRequest) (*admin.RunTierBackfillResponse, error) {
	out := new(admin.RunTierBackfillResponse)
	if err := c.call(ctx, "POST", "/api/admin/tier-backfill", in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) SchedulePickup(ctx context.Context, in *admin.SchedulePickupRequest) (*admin.SchedulePickupResponse, error) {
	out := new(admin.SchedulePickupResponse)
	if err := c.call(ctx, "POST", "/api/admin/fulfillment/pickup", in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) SendMemberEmail(ctx context.Context, in *admin.SendMemberEmailRequest) (*admin.SendMemberEmailResponse, error) {
	out := new(admin.SendMemberEmailResponse)
	if err := c.call(ctx, "POST", "/api/admin/members/{user_id}/email", in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) SetAccountDisabled(ctx context.Context, in *admin.SetAccountDisabledRequest) (*admin.SetAccountDisabledResponse, error) {
	out := new(admin.SetAccountDisabledResponse)
	if err := c.call(ctx, "PUT", "/api/admin/accounts/{username}/disabled", in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) SetBackgroundHeroColor(ctx context.Context, in *admin.SetBackgroundHeroColorRequest) (*admin.SetBackgroundHeroColorResponse, error) {
	out := new(admin.SetBackgroundHeroColorResponse)
	if err := c.call(ctx, "POST", "/api/admin/settings/background-hero-color", in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) SetColorwayCustoms(ctx context.Context, in *admin.SetColorwayCustomsRequest) (*admin.SetColorwayCustomsResponse, error) {
	out := new(admin.SetColorwayCustomsResponse)
	if err := c.call(ctx, "POST", "/api/admin/colorways/customs", in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) SetCountryActive(ctx context.Context, in *admin.SetCountryActiveRequest) (*admin.SetCountryActiveResponse, error) {
	out := new(admin.SetCountryActiveResponse)
	if err := c.call(ctx, "POST", "/api/admin/dictionaries/countries/{code}/active", in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) SetFulfillmentAssignee(ctx context.Context, in *admin.SetFulfillmentAssigneeRequest) (*admin.SetFulfillmentAssigneeResponse, error) {
	out := new(admin.SetFulfillmentAssigneeResponse)
	if err := c.call(ctx, "POST", "/api/admin/fulfillment/assignee", in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) SetFulfillmentChecklistItemDone(ctx context.Context, in *admin.SetFulfillmentChecklistItemDoneRequest) (*admin.SetFulfillmentChecklistItemDoneResponse, error) {
	out := new(admin.SetFulfillmentChecklistItemDoneResponse)
	if err := c.call(ctx, "POST", "/api/admin/fulfillment/checklist/done", in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) SetFulfillmentNotes(ctx context.Context, in *admin.SetFulfillmentNotesRequest) (*admin.SetFulfillmentNotesResponse, error) {
	out := new(admin.SetFulfillmentNotesResponse)
	if err := c.call(ctx, "POST", "/api/admin/fulfillment/notes", in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) SetMemberStatus(ctx context.Context, in *admin.SetMemberStatusRequest) (*admin.SetMemberStatusResponse, error) {
	out := new(admin.SetMemberStatusResponse)
	if err := c.call(ctx, "POST", "/api/admin/members/{user_id}/status", in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) SetShipmentActualCost(ctx context.Context, in *admin.SetShipmentActualCostRequest) (*admin.SetShipmentActualCostResponse, error) {
	out := new(admin.SetShipmentActualCostResponse)
	if err := c.call(ctx, "POST", "/api/admin/order/shipment/actual-cost", in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) SetTaskChecklistItemDone(ctx context.Context, in *admin.SetTaskChecklistItemDoneRequest) (*admin.SetTaskChecklistItemDoneResponse, error) {
	out := new(admin.SetTaskChecklistItemDoneResponse)
	if err := c.call(ctx, "POST", "/api/admin/task/checklist/done", in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) SetTrackingNumber(ctx context.Context, in *admin.SetTrackingNumberRequest) (*admin.SetTrackingNumberResponse, error) {
	out := new(admin.SetTrackingNumberResponse)
	if err := c.call(ctx, "POST", "/api/admin/orders/{order_uuid}/set-tracking-number", in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) ShipFulfillmentOrder(ctx context.Context, in *admin.ShipFulfillmentOrderRequest) (*admin.ShipFulfillmentOrderResponse, error) {
	out := new(admin.ShipFulfillmentOrderResponse)
	if err := c.call(ctx, "POST", "/api/admin/fulfillment/ship", in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) SoftDeleteMember(ctx context.Context, in *admin.SoftDeleteMemberRequest) (*admin.SoftDeleteMemberResponse, error) {
	out := new(admin.SoftDeleteMemberResponse)
	if err := c.call(ctx, "DELETE", "/api/admin/members/{user_id}", in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) SuggestStyleNumber(ctx context.Context, in *admin.SuggestStyleNumberRequest) (*admin.SuggestStyleNumberResponse, error) {
	out := new(admin.SuggestStyleNumberResponse)
	if err := c.call(ctx, "POST", "/api/admin/tech-card/suggest-style-number", in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) SyncColorwayCostFromOwningStyle(ctx context.Context, in *admin.SyncColorwayCostFromOwningStyleRequest) (*admin.SyncColorwayCostFromOwningStyleResponse, error) {
	out := new(admin.SyncColorwayCostFromOwningStyleResponse)
	if err := c.call(ctx, "POST", "/api/admin/colorways/{colorway_id}/cost/sync", in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) TransitionColorwayStatus(ctx context.Context, in *admin.TransitionColorwayStatusRequest) (*admin.TransitionColorwayStatusResponse, error) {
	out := new(admin.TransitionColorwayStatusResponse)
	if err := c.call(ctx, "POST", "/api/admin/colorways/{colorway_id}/status", in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) UnarchiveTask(ctx context.Context, in *admin.UnarchiveTaskRequest) (*admin.UnarchiveTaskResponse, error) {
	out := new(admin.UnarchiveTaskResponse)
	if err := c.call(ctx, "POST", "/api/admin/task/unarchive", in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) UpdateAccountPermissions(ctx context.Context, in *admin.UpdateAccountPermissionsRequest) (*admin.UpdateAccountPermissionsResponse, error) {
	out := new(admin.UpdateAccountPermissionsResponse)
	if err := c.call(ctx, "PUT", "/api/admin/accounts/{username}/permissions", in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) UpdateAcctAccount(ctx context.Context, in *admin.UpdateAcctAccountRequest) (*admin.UpdateAcctAccountResponse, error) {
	out := new(admin.UpdateAcctAccountResponse)
	if err := c.call(ctx, "POST", "/api/admin/accounting/accounts/update", in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) UpdateArchive(ctx context.Context, in *admin.UpdateArchiveRequest) (*admin.UpdateArchiveResponse, error) {
	out := new(admin.UpdateArchiveResponse)
	if err := c.call(ctx, "POST", "/api/admin/archive/update", in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) UpdateCollection(ctx context.Context, in *admin.UpdateCollectionRequest) (*admin.UpdateCollectionResponse, error) {
	out := new(admin.UpdateCollectionResponse)
	if err := c.call(ctx, "PATCH", "/api/admin/dictionaries/collections/{id}", in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) UpdateColor(ctx context.Context, in *admin.UpdateColorRequest) (*admin.UpdateColorResponse, error) {
	out := new(admin.UpdateColorResponse)
	if err := c.call(ctx, "PATCH", "/api/admin/dictionaries/colors/{code}", in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) UpdateColorway(ctx context.Context, in *admin.UpdateColorwayRequest) (*admin.UpdateColorwayResponse, error) {
	out := new(admin.UpdateColorwayResponse)
	if err := c.call(ctx, "PATCH", "/api/admin/colorways/{colorway_id}", in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) UpdateColorwayRecipe(ctx context.Context, in *admin.UpdateColorwayRecipeRequest) (*admin.UpdateColorwayRecipeResponse, error) {
	out := new(admin.UpdateColorwayRecipeResponse)
	if err := c.call(ctx, "PUT", "/api/admin/colorways/{colorway_id}/recipe", in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) UpdateFitting(ctx context.Context, in *admin.UpdateFittingRequest) (*admin.UpdateFittingResponse, error) {
	out := new(admin.UpdateFittingResponse)
	if err := c.call(ctx, "POST", "/api/admin/fitting/update", in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) UpdateFittingChangeRequest(ctx context.Context, in *admin.UpdateFittingChangeRequestRequest) (*admin.UpdateFittingChangeRequestResponse, error) {
	out := new(admin.UpdateFittingChangeRequestResponse)
	if err := c.call(ctx, "POST", "/api/admin/fitting/change-request/update", in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) UpdateMaterial(ctx context.Context, in *admin.UpdateMaterialRequest) (*admin.UpdateMaterialResponse, error) {
	out := new(admin.UpdateMaterialResponse)
	if err := c.call(ctx, "PUT", "/api/admin/materials", in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) UpdateModel(ctx context.Context, in *admin.UpdateModelRequest) (*admin.UpdateModelResponse, error) {
	out := new(admin.UpdateModelResponse)
	if err := c.call(ctx, "POST", "/api/admin/model/update", in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) UpdateProductionRun(ctx context.Context, in *admin.UpdateProductionRunRequest) (*admin.UpdateProductionRunResponse, error) {
	out := new(admin.UpdateProductionRunResponse)
	if err := c.call(ctx, "PUT", "/api/admin/production-runs/{id}", in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) UpdatePromoCode(ctx context.Context, in *admin.UpdatePromoCodeRequest) (*admin.UpdatePromoCodeResponse, error) {
	out := new(admin.UpdatePromoCodeResponse)
	if err := c.call(ctx, "PUT", "/api/admin/promo/update", in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) UpdateSample(ctx context.Context, in *admin.UpdateSampleRequest) (*admin.UpdateSampleResponse, error) {
	out := new(admin.UpdateSampleResponse)
	if err := c.call(ctx, "POST", "/api/admin/sample/update", in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) UpdateSettings(ctx context.Context, in *admin.UpdateSettingsRequest) (*admin.UpdateSettingsResponse, error) {
	out := new(admin.UpdateSettingsResponse)
	if err := c.call(ctx, "POST", "/api/admin/settings/update", in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) UpdateShipmentCarrier(ctx context.Context, in *admin.UpdateShipmentCarrierRequest) (*admin.UpdateShipmentCarrierResponse, error) {
	out := new(admin.UpdateShipmentCarrierResponse)
	if err := c.call(ctx, "POST", "/api/admin/settings/shipment-carrier/update", in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) UpdateStyle(ctx context.Context, in *admin.UpdateStyleRequest) (*admin.UpdateStyleResponse, error) {
	out := new(admin.UpdateStyleResponse)
	if err := c.call(ctx, "PATCH", "/api/admin/styles/{style_id}", in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) UpdateStyleSizeChart(ctx context.Context, in *admin.UpdateStyleSizeChartRequest) (*admin.UpdateStyleSizeChartResponse, error) {
	out := new(admin.UpdateStyleSizeChartResponse)
	if err := c.call(ctx, "PUT", "/api/admin/styles/{style_id}/size-chart", in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) UpdateSupportTicket(ctx context.Context, in *admin.UpdateSupportTicketRequest) (*admin.UpdateSupportTicketResponse, error) {
	out := new(admin.UpdateSupportTicketResponse)
	if err := c.call(ctx, "POST", "/api/admin/support/tickets/{id}/update", in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) UpdateSupportTicketStatus(ctx context.Context, in *admin.UpdateSupportTicketStatusRequest) (*admin.UpdateSupportTicketStatusResponse, error) {
	out := new(admin.UpdateSupportTicketStatusResponse)
	if err := c.call(ctx, "POST", "/api/admin/support/tickets/{id}/update-status", in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) UpdateTag(ctx context.Context, in *admin.UpdateTagRequest) (*admin.UpdateTagResponse, error) {
	out := new(admin.UpdateTagResponse)
	if err := c.call(ctx, "PATCH", "/api/admin/dictionaries/tags/{id}", in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) UpdateTask(ctx context.Context, in *admin.UpdateTaskRequest) (*admin.UpdateTaskResponse, error) {
	out := new(admin.UpdateTaskResponse)
	if err := c.call(ctx, "POST", "/api/admin/task/update", in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) UpdateTechCard(ctx context.Context, in *admin.UpdateTechCardRequest) (*admin.UpdateTechCardResponse, error) {
	out := new(admin.UpdateTechCardResponse)
	if err := c.call(ctx, "POST", "/api/admin/tech-card/update", in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) UpdateTierConfig(ctx context.Context, in *admin.UpdateTierConfigRequest) (*admin.UpdateTierConfigResponse, error) {
	out := new(admin.UpdateTierConfigResponse)
	if err := c.call(ctx, "POST", "/api/admin/tier-config", in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) UpdateVariant(ctx context.Context, in *admin.UpdateVariantRequest) (*admin.UpdateVariantResponse, error) {
	out := new(admin.UpdateVariantResponse)
	if err := c.call(ctx, "PATCH", "/api/admin/variants/{variant_id}", in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) UpdateVariantStock(ctx context.Context, in *admin.UpdateVariantStockRequest) (*admin.UpdateVariantStockResponse, error) {
	out := new(admin.UpdateVariantStockResponse)
	if err := c.call(ctx, "POST", "/api/admin/stock/update", in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) UploadContentImage(ctx context.Context, in *admin.UploadContentImageRequest) (*admin.UploadContentImageResponse, error) {
	out := new(admin.UploadContentImageResponse)
	if err := c.call(ctx, "POST", "/api/admin/content/image", in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) UploadContentVideo(ctx context.Context, in *admin.UploadContentVideoRequest) (*admin.UploadContentVideoResponse, error) {
	out := new(admin.UploadContentVideoResponse)
	if err := c.call(ctx, "POST", "/api/admin/content/video", in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) UploadPattern(ctx context.Context, in *admin.UploadPatternRequest) (*admin.UploadPatternResponse, error) {
	out := new(admin.UploadPatternResponse)
	if err := c.call(ctx, "POST", "/api/admin/content/pattern", in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) UpsertAlertSettings(ctx context.Context, in *admin.UpsertAlertSettingsRequest) (*admin.UpsertAlertSettingsResponse, error) {
	out := new(admin.UpsertAlertSettingsResponse)
	if err := c.call(ctx, "POST", "/api/admin/dashboard/alert-settings/upsert", in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) UpsertChannelSpend(ctx context.Context, in *admin.UpsertChannelSpendRequest) (*admin.UpsertChannelSpendResponse, error) {
	out := new(admin.UpsertChannelSpendResponse)
	if err := c.call(ctx, "POST", "/api/admin/metrics/channel-spend/upsert", in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) UpsertCostingFxRates(ctx context.Context, in *admin.UpsertCostingFxRatesRequest) (*admin.UpsertCostingFxRatesResponse, error) {
	out := new(admin.UpsertCostingFxRatesResponse)
	if err := c.call(ctx, "POST", "/api/admin/costing/fx-rates", in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) UpsertEmployee(ctx context.Context, in *admin.UpsertEmployeeRequest) (*admin.UpsertEmployeeResponse, error) {
	out := new(admin.UpsertEmployeeResponse)
	if err := c.call(ctx, "POST", "/api/admin/metrics/employees/upsert", in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) UpsertInventoryTargets(ctx context.Context, in *admin.UpsertInventoryTargetsRequest) (*admin.UpsertInventoryTargetsResponse, error) {
	out := new(admin.UpsertInventoryTargetsResponse)
	if err := c.call(ctx, "POST", "/api/admin/metrics/inventory/targets/upsert", in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) UpsertOpexLines(ctx context.Context, in *admin.UpsertOpexLinesRequest) (*admin.UpsertOpexLinesResponse, error) {
	out := new(admin.UpsertOpexLinesResponse)
	if err := c.call(ctx, "POST", "/api/admin/metrics/opex/lines/upsert", in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) UpsertOpexRecurring(ctx context.Context, in *admin.UpsertOpexRecurringRequest) (*admin.UpsertOpexRecurringResponse, error) {
	out := new(admin.UpsertOpexRecurringResponse)
	if err := c.call(ctx, "POST", "/api/admin/metrics/opex/recurring/upsert", in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) UpsertPackagingBom(ctx context.Context, in *admin.UpsertPackagingBomRequest) (*admin.UpsertPackagingBomResponse, error) {
	out := new(admin.UpsertPackagingBomResponse)
	if err := c.call(ctx, "POST", "/api/admin/inventory/packaging-bom/upsert", in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) UpsertPackagingRecipe(ctx context.Context, in *admin.UpsertPackagingRecipeRequest) (*admin.UpsertPackagingRecipeResponse, error) {
	out := new(admin.UpsertPackagingRecipeResponse)
	if err := c.call(ctx, "POST", "/api/admin/inventory/packaging-recipe/upsert", in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) UpsertPaymentMethodFees(ctx context.Context, in *admin.UpsertPaymentMethodFeesRequest) (*admin.UpsertPaymentMethodFeesResponse, error) {
	out := new(admin.UpsertPaymentMethodFeesResponse)
	if err := c.call(ctx, "POST", "/api/admin/settings/payment-method-fees", in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) UpsertStyleAssembly(ctx context.Context, in *admin.UpsertStyleAssemblyRequest) (*admin.UpsertStyleAssemblyResponse, error) {
	out := new(admin.UpsertStyleAssemblyResponse)
	if err := c.call(ctx, "POST", "/api/admin/tech-card/style-assembly/upsert", in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) UpsertVatRates(ctx context.Context, in *admin.UpsertVatRatesRequest) (*admin.UpsertVatRatesResponse, error) {
	out := new(admin.UpsertVatRatesResponse)
	if err := c.call(ctx, "POST", "/api/admin/vat-rates", in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) VoidShippingLabel(ctx context.Context, in *admin.VoidShippingLabelRequest) (*admin.VoidShippingLabelResponse, error) {
	out := new(admin.VoidShippingLabelResponse)
	if err := c.call(ctx, "POST", "/api/admin/fulfillment/label/void", in, out); err != nil {
		return nil, err
	}
	return out, nil
}

// ---- auth (4 rpc) ----

func (c *Client) AuthChangePassword(ctx context.Context, in *auth.ChangePasswordRequest) (*auth.ChangePasswordResponse, error) {
	out := new(auth.ChangePasswordResponse)
	if err := c.call(ctx, "PUT", "/api/auth/change-password", in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) AuthCreate(ctx context.Context, in *auth.CreateRequest) (*auth.CreateResponse, error) {
	out := new(auth.CreateResponse)
	if err := c.call(ctx, "POST", "/api/auth/create", in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) AuthDelete(ctx context.Context, in *auth.DeleteRequest) (*auth.DeleteResponse, error) {
	out := new(auth.DeleteResponse)
	if err := c.call(ctx, "DELETE", "/api/auth/delete/{username}", in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) AuthLogin(ctx context.Context, in *auth.LoginRequest) (*auth.LoginResponse, error) {
	out := new(auth.LoginResponse)
	if err := c.call(ctx, "POST", "/api/auth/login", in, out); err != nil {
		return nil, err
	}
	return out, nil
}

// ---- frontend (30 rpc) ----

func (c *Client) SFAddSavedAddress(ctx context.Context, in *frontend.AddSavedAddressRequest) (*frontend.AddSavedAddressResponse, error) {
	out := new(frontend.AddSavedAddressResponse)
	if err := c.call(ctx, "POST", "/api/frontend/account/addresses", in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) SFCancelOrderByUser(ctx context.Context, in *frontend.CancelOrderByUserRequest) (*frontend.CancelOrderByUserResponse, error) {
	out := new(frontend.CancelOrderByUserResponse)
	if err := c.call(ctx, "POST", "/api/frontend/order/{order_uuid}/{b64_email}/cancel", in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) SFCancelOrderInvoice(ctx context.Context, in *frontend.CancelOrderInvoiceRequest) (*frontend.CancelOrderInvoiceResponse, error) {
	out := new(frontend.CancelOrderInvoiceResponse)
	if err := c.call(ctx, "POST", "/api/frontend/order/{order_uuid}/invoice/cancel", in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) SFDeleteSavedAddress(ctx context.Context, in *frontend.DeleteSavedAddressRequest) (*frontend.DeleteSavedAddressResponse, error) {
	out := new(frontend.DeleteSavedAddressResponse)
	if err := c.call(ctx, "DELETE", "/api/frontend/account/addresses/{id}", in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) SFGetAccount(ctx context.Context, in *frontend.GetAccountRequest) (*frontend.GetAccountResponse, error) {
	out := new(frontend.GetAccountResponse)
	if err := c.call(ctx, "GET", "/api/frontend/account/me", in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) SFGetArchive(ctx context.Context, in *frontend.GetArchiveRequest) (*frontend.GetArchiveResponse, error) {
	out := new(frontend.GetArchiveResponse)
	if err := c.call(ctx, "GET", "/api/frontend/archive/{code}", in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) SFGetArchivesPaged(ctx context.Context, in *frontend.GetArchivesPagedRequest) (*frontend.GetArchivesPagedResponse, error) {
	out := new(frontend.GetArchivesPagedResponse)
	if err := c.call(ctx, "GET", "/api/frontend/archive/paged", in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) SFGetColorway(ctx context.Context, in *frontend.GetColorwayRequest) (*frontend.GetColorwayResponse, error) {
	out := new(frontend.GetColorwayResponse)
	if err := c.call(ctx, "GET", "/api/frontend/colorways/{base_sku}", in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) SFGetColorwaysPaged(ctx context.Context, in *frontend.GetColorwaysPagedRequest) (*frontend.GetColorwaysPagedResponse, error) {
	out := new(frontend.GetColorwaysPagedResponse)
	if err := c.call(ctx, "GET", "/api/frontend/colorways/paged", in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) SFGetHero(ctx context.Context, in *frontend.GetHeroRequest) (*frontend.GetHeroResponse, error) {
	out := new(frontend.GetHeroResponse)
	if err := c.call(ctx, "GET", "/api/frontend/hero", in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) SFGetOrderByUUIDAndEmail(ctx context.Context, in *frontend.GetOrderByUUIDAndEmailRequest) (*frontend.GetOrderByUUIDAndEmailResponse, error) {
	out := new(frontend.GetOrderByUUIDAndEmailResponse)
	if err := c.call(ctx, "GET", "/api/frontend/order/{order_uuid}/{b64_email}", in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) SFGetOrderInvoice(ctx context.Context, in *frontend.GetOrderInvoiceRequest) (*frontend.GetOrderInvoiceResponse, error) {
	out := new(frontend.GetOrderInvoiceResponse)
	if err := c.call(ctx, "POST", "/api/frontend/order/{order_uuid}/{payment_method}/invoice", in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) SFListMyOrders(ctx context.Context, in *frontend.ListMyOrdersRequest) (*frontend.ListMyOrdersResponse, error) {
	out := new(frontend.ListMyOrdersResponse)
	if err := c.call(ctx, "GET", "/api/frontend/account/orders", in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) SFListSavedAddresses(ctx context.Context, in *frontend.ListSavedAddressesRequest) (*frontend.ListSavedAddressesResponse, error) {
	out := new(frontend.ListSavedAddressesResponse)
	if err := c.call(ctx, "GET", "/api/frontend/account/addresses", in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) SFNotifyMe(ctx context.Context, in *frontend.NotifyMeRequest) (*frontend.NotifyMeResponse, error) {
	out := new(frontend.NotifyMeResponse)
	if err := c.call(ctx, "POST", "/api/frontend/notify-me", in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) SFRefreshAccountSession(ctx context.Context, in *frontend.RefreshAccountSessionRequest) (*frontend.RefreshAccountSessionResponse, error) {
	out := new(frontend.RefreshAccountSessionResponse)
	if err := c.call(ctx, "POST", "/api/frontend/account/session/refresh", in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) SFRequestAccountLogin(ctx context.Context, in *frontend.RequestAccountLoginRequest) (*frontend.RequestAccountLoginResponse, error) {
	out := new(frontend.RequestAccountLoginResponse)
	if err := c.call(ctx, "POST", "/api/frontend/account/login/request", in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) SFRevokeAccountSession(ctx context.Context, in *frontend.RevokeAccountSessionRequest) (*frontend.RevokeAccountSessionResponse, error) {
	out := new(frontend.RevokeAccountSessionResponse)
	if err := c.call(ctx, "POST", "/api/frontend/account/session/revoke", in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) SFSetDefaultSavedAddress(ctx context.Context, in *frontend.SetDefaultSavedAddressRequest) (*frontend.SetDefaultSavedAddressResponse, error) {
	out := new(frontend.SetDefaultSavedAddressResponse)
	if err := c.call(ctx, "POST", "/api/frontend/account/addresses/{id}/default", in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) SFSubmitOrder(ctx context.Context, in *frontend.SubmitOrderRequest) (*frontend.SubmitOrderResponse, error) {
	out := new(frontend.SubmitOrderResponse)
	if err := c.call(ctx, "POST", "/api/frontend/order/new", in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) SFSubmitOrderReview(ctx context.Context, in *frontend.SubmitOrderReviewRequest) (*frontend.SubmitOrderReviewResponse, error) {
	out := new(frontend.SubmitOrderReviewResponse)
	if err := c.call(ctx, "POST", "/api/frontend/order/{order_uuid}/review", in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) SFSubmitSupportTicket(ctx context.Context, in *frontend.SubmitSupportTicketRequest) (*frontend.SubmitSupportTicketResponse, error) {
	out := new(frontend.SubmitSupportTicketResponse)
	if err := c.call(ctx, "POST", "/api/frontend/support/ticket", in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) SFSubscribeNewsletter(ctx context.Context, in *frontend.SubscribeNewsletterRequest) (*frontend.SubscribeNewsletterResponse, error) {
	out := new(frontend.SubscribeNewsletterResponse)
	if err := c.call(ctx, "POST", "/api/frontend/newsletter/subscribe", in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) SFUnsubscribeNewsletter(ctx context.Context, in *frontend.UnsubscribeNewsletterRequest) (*frontend.UnsubscribeNewsletterResponse, error) {
	out := new(frontend.UnsubscribeNewsletterResponse)
	if err := c.call(ctx, "POST", "/api/frontend/newsletter/unsubscribe", in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) SFUpdateAccount(ctx context.Context, in *frontend.UpdateAccountRequest) (*frontend.UpdateAccountResponse, error) {
	out := new(frontend.UpdateAccountResponse)
	if err := c.call(ctx, "PUT", "/api/frontend/account/me", in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) SFUpdateSavedAddress(ctx context.Context, in *frontend.UpdateSavedAddressRequest) (*frontend.UpdateSavedAddressResponse, error) {
	out := new(frontend.UpdateSavedAddressResponse)
	if err := c.call(ctx, "PUT", "/api/frontend/account/addresses/{id}", in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) SFValidateOrderByUUID(ctx context.Context, in *frontend.ValidateOrderByUUIDRequest) (*frontend.ValidateOrderByUUIDResponse, error) {
	out := new(frontend.ValidateOrderByUUIDResponse)
	if err := c.call(ctx, "POST", "/api/frontend/orders/validate/{order_uuid}", in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) SFValidateOrderItemsInsert(ctx context.Context, in *frontend.ValidateOrderItemsInsertRequest) (*frontend.ValidateOrderItemsInsertResponse, error) {
	out := new(frontend.ValidateOrderItemsInsertResponse)
	if err := c.call(ctx, "POST", "/api/frontend/orders/validate-items", in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) SFVerifyAccountLoginCode(ctx context.Context, in *frontend.VerifyAccountLoginCodeRequest) (*frontend.VerifyAccountLoginResponse, error) {
	out := new(frontend.VerifyAccountLoginResponse)
	if err := c.call(ctx, "POST", "/api/frontend/account/login/verify-code", in, out); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *Client) SFVerifyAccountMagicLink(ctx context.Context, in *frontend.VerifyAccountMagicLinkRequest) (*frontend.VerifyAccountLoginResponse, error) {
	out := new(frontend.VerifyAccountLoginResponse)
	if err := c.call(ctx, "POST", "/api/frontend/account/login/verify-magic", in, out); err != nil {
		return nil, err
	}
	return out, nil
}
