package store

import (
	"context"
	"database/sql"
	"testing"
	"time"

	"github.com/jekabolt/grbpwr-manager/internal/entity"
	"github.com/stretchr/testify/require"
)

// insertAdminFixture creates a uniquely named admin account and registers its
// removal. The name is generated by MySQL so two runs of the suite against the
// same container cannot collide on the UNIQUE username.
func insertAdminFixture(ctx context.Context, t *testing.T, prefix string) (int, string) {
	t.Helper()
	res, err := testDB.ExecContext(ctx,
		`INSERT INTO admins (username, password_hash) VALUES (CONCAT(?, '-', UUID_SHORT()), 'x')`, prefix)
	require.NoError(t, err)
	id, err := res.LastInsertId()
	require.NoError(t, err)
	var username string
	require.NoError(t, testDB.QueryRowContext(ctx,
		`SELECT username FROM admins WHERE id = ?`, id).Scan(&username))
	t.Cleanup(func() {
		_, _ = testDB.Exec(`DELETE FROM admins WHERE id = ?`, id)
	})
	return int(id), username
}

// TestLibraryFilePeople covers the whole of Ф3 on the store side: who uploaded a
// file (as a link, next to the historical string), who keeps it, and what people
// say they do.
//
// It has to be an integration test. Every claim here is a claim about SQL and
// about the schema's delete rules — ON DELETE SET NULL on the uploader link,
// ON DELETE CASCADE on ownership — and none of them is observable in Go.
func TestLibraryFilePeople(t *testing.T) {
	filesGuard(t)

	ctx, cancel := context.WithTimeout(context.Background(), 120*time.Second)
	defer cancel()

	s, err := NewForTest(ctx, *testCfg)
	require.NoError(t, err)

	pashaID, pasha := insertAdminFixture(ctx, t, "test-pasha")
	kirillID, kirill := insertAdminFixture(ctx, t, "test-kirill")

	t.Run("a new file records the uploader as a link, not only as a string", func(t *testing.T) {
		id, err := s.Files().AddFile(ctx, &entity.LibraryFileInsert{
			ObjectKey:   "files-library/test-people-" + t.Name(),
			FileName:    "people.pdf",
			ContentType: "application/pdf",
			UploadedBy:  pasha,
		}, nil, nil)
		require.NoError(t, err)
		t.Cleanup(func() { _, _ = testDB.Exec(`DELETE FROM library_file WHERE id = ?`, id) })

		f, err := s.Files().GetFileById(ctx, id)
		require.NoError(t, err)
		require.Equal(t, pasha, f.UploadedBy)
		require.True(t, f.UploadedById.Valid, "the id half of authorship must be derived from the username half")
		require.EqualValues(t, pashaID, f.UploadedById.Int64)
	})

	t.Run("an unknown uploader leaves the link empty rather than pointing nowhere", func(t *testing.T) {
		id, err := s.Files().AddFile(ctx, &entity.LibraryFileInsert{
			ObjectKey:  "files-library/test-ghost-" + t.Name(),
			FileName:   "ghost.pdf",
			UploadedBy: "nobody-with-this-name",
		}, nil, nil)
		require.NoError(t, err)
		t.Cleanup(func() { _, _ = testDB.Exec(`DELETE FROM library_file WHERE id = ?`, id) })

		f, err := s.Files().GetFileById(ctx, id)
		require.NoError(t, err)
		require.Equal(t, "nobody-with-this-name", f.UploadedBy)
		require.False(t, f.UploadedById.Valid)
	})

	t.Run("owners replace, resolve with their specialties, and may be none", func(t *testing.T) {
		require.NoError(t, s.Admin().SetSpecialties(ctx, kirillID, nil, []string{"конструктор"}))

		fileID := insertLibraryFileFixture(ctx, t, "owned.pdf", 10, pasha)

		require.NoError(t, s.Files().SetFileOwners(ctx, fileID, []int{kirillID, pashaID}, pasha))
		f, err := s.Files().GetFileById(ctx, fileID)
		require.NoError(t, err)
		require.Len(t, f.Owners, 2)
		byName := map[string]entity.AdminRef{}
		for _, o := range f.Owners {
			byName[o.Username] = o
		}
		require.Equal(t, []string{"конструктор"}, byName[kirill].Specialties)
		require.Empty(t, byName[pasha].Specialties)

		// Replace, not merge: the picker showed the caller the whole current set.
		require.NoError(t, s.Files().SetFileOwners(ctx, fileID, []int{pashaID}, kirill))
		f, err = s.Files().GetFileById(ctx, fileID)
		require.NoError(t, err)
		require.Len(t, f.Owners, 1)
		require.Equal(t, pasha, f.Owners[0].Username)

		// Nobody keeping the file is a legal state, not an error.
		require.NoError(t, s.Files().SetFileOwners(ctx, fileID, nil, kirill))
		f, err = s.Files().GetFileById(ctx, fileID)
		require.NoError(t, err)
		require.Empty(t, f.Owners)

		// A file that is gone must say so, not report a successful write into nothing.
		require.ErrorIs(t, s.Files().SetFileOwners(ctx, 2147483600, []int{pashaID}, kirill), sql.ErrNoRows)

		// A non-existent account must FAIL: "owner assigned" onto nobody is the worst
		// possible answer, because the card would then name somebody to ask and there
		// would be nobody.
		require.Error(t, s.Files().SetFileOwners(ctx, fileID, []int{2147483600}, kirill))
	})

	t.Run("deleting an account nulls the link, drops ownership, keeps the historical name", func(t *testing.T) {
		leaverID, leaver := insertAdminFixture(ctx, t, "test-leaver")

		fileID, err := s.Files().AddFile(ctx, &entity.LibraryFileInsert{
			ObjectKey:  "files-library/test-leaver-" + t.Name(),
			FileName:   "leaver.pdf",
			UploadedBy: leaver,
		}, nil, nil)
		require.NoError(t, err)
		t.Cleanup(func() { _, _ = testDB.Exec(`DELETE FROM library_file WHERE id = ?`, fileID) })

		require.NoError(t, s.Files().SetFileOwners(ctx, fileID, []int{leaverID, pashaID}, pasha))
		require.NoError(t, s.Admin().SetSpecialties(ctx, leaverID, nil, []string{"фотограф"}))

		_, err = testDB.ExecContext(ctx, `DELETE FROM admins WHERE id = ?`, leaverID)
		require.NoError(t, err)

		f, err := s.Files().GetFileById(ctx, fileID)
		require.NoError(t, err)
		// The STRING survives: who uploaded this is a historical fact and outlives
		// the account. The LINK does not: there is nobody to link to any more.
		require.Equal(t, leaver, f.UploadedBy)
		require.False(t, f.UploadedById.Valid)
		// Ownership is a relation and dies with the person; the other owner stays.
		require.Len(t, f.Owners, 1)
		require.Equal(t, pasha, f.Owners[0].Username)

		var links int
		require.NoError(t, testDB.QueryRowContext(ctx,
			`SELECT COUNT(*) FROM admin_specialty_link WHERE admin_id = ?`, leaverID).Scan(&links))
		require.Zero(t, links, "an account's specialty links must go with the account")
	})

	t.Run("specialties replace and collapse onto the existing vocabulary entry", func(t *testing.T) {
		// «Конструктор» must resolve onto the seeded «конструктор» rather than fork
		// the vocabulary — the collation is what makes that true, so it is asserted.
		require.NoError(t, s.Admin().SetSpecialties(ctx, kirillID, nil, []string{"Конструктор", "фотограф"}))
		var stored int
		require.NoError(t, testDB.QueryRowContext(ctx,
			`SELECT COUNT(*) FROM admin_specialty WHERE name = 'конструктор'`).Scan(&stored))
		require.Equal(t, 1, stored)

		accounts, err := s.Admin().ListAccounts(ctx)
		require.NoError(t, err)
		var found *entity.AdminAccount
		for i := range accounts {
			if accounts[i].Username == kirill {
				found = &accounts[i]
			}
		}
		require.NotNil(t, found)
		require.ElementsMatch(t, []string{"конструктор", "фотограф"}, found.Specialties)

		// Replace: the set shrinks when the person says it does.
		require.NoError(t, s.Admin().SetSpecialties(ctx, kirillID, nil, nil))
		account, err := s.Admin().GetAccountWithPermissions(ctx, kirill)
		require.NoError(t, err)
		require.Empty(t, account.Specialties)

		names, err := s.Admin().ListSpecialties(ctx)
		require.NoError(t, err)
		require.Contains(t, names, "технолог", "the seeded vocabulary must be reachable by the picker")
	})

	t.Run("the picker read excludes disabled accounts", func(t *testing.T) {
		goneID, gone := insertAdminFixture(ctx, t, "test-disabled")
		_, err := testDB.ExecContext(ctx, `UPDATE admins SET disabled = TRUE WHERE id = ?`, goneID)
		require.NoError(t, err)

		refs, err := s.Admin().ListAdminRefs(ctx)
		require.NoError(t, err)
		names := make([]string, 0, len(refs))
		for _, r := range refs {
			names = append(names, r.Username)
		}
		require.NotContains(t, names, gone, "a picker must not offer somebody who can no longer log in")
		require.Contains(t, names, kirill)

		// Он всё ещё виден в управлении аккаунтами — исчезает ИМЕННО из пикера.
		accounts, err := s.Admin().ListAccounts(ctx)
		require.NoError(t, err)
		accountNames := make([]string, 0, len(accounts))
		for _, a := range accounts {
			accountNames = append(accountNames, a.Username)
		}
		require.Contains(t, accountNames, gone)
	})

	t.Run("the shared vocabulary refuses to grow past its cap", func(t *testing.T) {
		var total int
		require.NoError(t, testDB.QueryRowContext(ctx, `SELECT COUNT(*) FROM admin_specialty`).Scan(&total))
		room := entity.MaxAdminSpecialtyVocabulary - total + 1
		if room < 1 {
			t.Skip("vocabulary already at the cap")
		}
		tooMany := make([]string, 0, room)
		for i := range room {
			tooMany = append(tooMany, "перебор-"+t.Name()+"-"+string(rune('a'+i%26))+string(rune('a'+i/26)))
		}
		err := s.Admin().SetSpecialties(ctx, kirillID, nil, tooMany)
		require.ErrorIs(t, err, entity.ErrAdminSpecialtyVocabularyFull)

		// Отказ обязан быть ПОЛНЫМ: транзакция откатилась, словарь не подрос ни на строку.
		var after int
		require.NoError(t, testDB.QueryRowContext(ctx, `SELECT COUNT(*) FROM admin_specialty`).Scan(&after))
		require.Equal(t, total, after)
	})
}

// TestLibraryFileDeleteRefusalNamesItsHolders pins the refusal path of DeleteFile.
//
// Оно живёт в файле Ф3, потому что здесь и нашлось: отказ собирал список
// держателей через QueryListNamed[int], а тот сканирует StructScan-ом и на
// не-структуре ПАНИКУЕТ — но только когда строки есть. Пустая выборка (файл
// никем не держится) проходила молча, поэтому весь happy path выглядел рабочим,
// а падал бы ровно тот случай, ради которого код написан. Покрытия у него не было.
func TestLibraryFileDeleteRefusalNamesItsHolders(t *testing.T) {
	filesGuard(t)

	ctx, cancel := context.WithTimeout(context.Background(), 90*time.Second)
	defer cancel()

	s, err := NewForTest(ctx, *testCfg)
	require.NoError(t, err)

	fileID := insertLibraryFileFixture(ctx, t, "held.pdf", 10, "pasha")
	res, err := testDB.ExecContext(ctx,
		`INSERT INTO task (title, board, status) VALUES ('test-holder', 'design', 'todo')`)
	require.NoError(t, err)
	taskID, err := res.LastInsertId()
	require.NoError(t, err)
	t.Cleanup(func() { _, _ = testDB.Exec(`DELETE FROM task WHERE id = ?`, taskID) })
	_, err = testDB.ExecContext(ctx,
		`INSERT INTO task_file (task_id, file_id) VALUES (?, ?)`, taskID, fileID)
	require.NoError(t, err)

	_, err = s.Files().DeleteFile(ctx, fileID)
	require.ErrorIs(t, err, entity.ErrLibraryFileInUse)
	// Сообщение обязано НАЗВАТЬ держателя: голое «не удаляется» не даёт человеку
	// ни одного следующего шага.
	require.Contains(t, err.Error(), "#")
}

// TestFilesPeopleMigrationsAreRerunnable re-applies 0314 and 0315 over a schema
// they have ALREADY been applied to, which is exactly what a mid-file failure
// leaves behind: MySQL auto-commits DDL, so the half-applied schema keeps no
// gorp_migrations row and the next boot runs the file again from the top. A
// migration that cannot survive that does not fail in a test — it stops the
// process from starting.
func TestFilesPeopleMigrationsAreRerunnable(t *testing.T) {
	filesGuard(t)

	ctx, cancel := context.WithTimeout(context.Background(), 120*time.Second)
	defer cancel()

	_, uploader := insertAdminFixture(ctx, t, "test-rerun")
	// A row shaped like history: the name is there, the link is not — which is what
	// every file uploaded before 0314 looks like.
	legacy := insertLibraryFileFixture(ctx, t, "legacy.pdf", 10, uploader)
	_, err := testDB.ExecContext(ctx,
		`UPDATE library_file SET uploaded_by_id = NULL WHERE id = ?`, legacy)
	require.NoError(t, err)

	seedCount := func() int {
		var n int
		require.NoError(t, testDB.QueryRowContext(ctx,
			`SELECT COUNT(*) FROM admin_specialty WHERE name = 'дизайнер'`).Scan(&n))
		return n
	}
	require.Equal(t, 1, seedCount())

	for i := range 2 {
		_, err := testDB.ExecContext(ctx,
			`DELETE FROM gorp_migrations WHERE id IN ('0314_files_people.sql', '0315_admin_specialties.sql')`)
		require.NoError(t, err)
		require.NoError(t, Migrate(testDB), "re-applying 0314/0315 over an applied schema (pass %d)", i+1)

		var uploadedByID sql.NullInt64
		var uploadedBy string
		require.NoError(t, testDB.QueryRowContext(ctx,
			`SELECT uploaded_by, uploaded_by_id FROM library_file WHERE id = ?`, legacy).
			Scan(&uploadedBy, &uploadedByID))
		require.Equal(t, uploader, uploadedBy, "the backfill must never touch the historical string")
		require.True(t, uploadedByID.Valid, "the backfill must resolve a known username to its account")
		require.Equal(t, 1, seedCount(), "INSERT IGNORE must not grow the vocabulary on a repeat")
	}
}
